languageCode = 'en-us'
title = 'My personal blog for programming'

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
lineNos = true
lineNumbersInTable = false
noClasses = true
style = 'monokai'
tabWidth = 4

[params]
description = 'Personal blog to end brainrot and AI dependency.'
author = 'Vinicius Bregoli'
github = 'https://github.com/viniciusbregoli'
linkedin = 'https://linkedin.com/in/viniciusbregoli'
